services/web/src/config/urls.py
from django.contrib import admin
from django.urls import path, include
import vagas

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oportunidades/', include('vagas.urls')),
    path('', vagas.views.index, name='homepage'),
]

services/web/src/vagas/urls.py
from django.urls import path
from .views import create_view, detail_view, edit_view, delete_view

urlpatterns = [
    path('new', create_view, name='oportunidades_new'),
    path('<int:pk>', detail_view, name='oportunidades_detail'),
    path('<int:pk>/edit', edit_view, name='oportunidades_edit'),
    path('<int:pk>/delete', delete_view, name='oportunidades_delete'),
]

services/web/src/vagas/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from typing import Any
import re
from datetime import datetime
from vagas.validators import is_equal_to_or_later_than_current_datetime

class TelefoneField(models.CharField):
    
    def get_prep_value(self, value: Any) -> Any:
        regex = re.compile('\D+')

        return regex.sub('', str(value))
    
    def from_db_value(self, value: Any, expression, connection):
        if value:
            phone_regex = re.compile(r'^(\d{2})(\d{1,})(\d{4})$')
            p1, p2, p3 = phone_regex.search(value).groups()
            
            return f'({p1}) {p2}-{p3}'
        
        return value

class Vaga(models.Model):
    """A job opportunity model."""

    class Status(models.TextChoices):
        APPLIED = 'C', 'Candidatado'
        WAITING = 'W', 'Aguardando retorno'
        INTERVIEW_SCHEDULED = 'S', 'Entrevista agendada'
        REJECTED = 'R', 'Rejeitado'
        APPROVED = 'A', 'Aprovado'

    empresa_nome = models.CharField(
        max_length=100,
        blank=False,
        error_messages={
            'blank': 'O campo Nome da empresa é obrigatório.',
            'max_length': 'O campo Nome da empresa pode conter no máximo %(limit_value)s caracteres.'
        }
    )

    empresa_endereco = models.CharField(
        max_length=200,
        null=False,
        blank=True,
        error_messages={
            'max_length': 'O campo Endereço da empresa pode conter no máximo %(limit_value)s caracteres.'
        }
    )

    empresa_email = models.EmailField(
        null=False,
        blank=True,
        error_messages={
            'invalid': 'O campo Email da empresa deve conter um email válido.'
        }
    )
    
    empresa_site = models.URLField(
        null=False,
        blank=False,
        error_messages={
            'blank': 'O campo Site da empresa é obrigatório.',
            'invalid': 'O campo Site da empresa deve conter um endereço web válido.'
        }
    )
    empresa_telefone_celular = TelefoneField(
        max_length=15,
        null=False,
        blank=True,
        validators=[RegexValidator(
            regex=r'^\(\d{2}\) 9\d{4}-\d{4}$',
            message='O campo Telefone celular da empresa deve conter um número válido. Ex.: (DDD) 99999-9999',
            code='invalid'
        )]
    )

    empresa_telefone_comercial = TelefoneField(
        max_length=14,
        null=False,
        blank=True,
        validators=[RegexValidator(
            regex=r'^\(\d{2}\) \d{4}-\d{4}$',
            message='O campo Telefone comercial da empresa deve conter um número válido. Ex.: (DDD) 9999-9999',
            code='invalid'
        )]
    )

    cargo_titulo = models.CharField(
        max_length=50,
        null=False,
        blank=False,
        error_messages={
            'blank': 'O campo Título do cargo é obrigatório.',
            'max_length': 'O campo Título do cargo pode conter no máximo %(limit_value)s caracteres.'
        }
    )

    cargo_descricao = models.TextField(
        null=False,
        blank=True
    )

    site_referencia = models.URLField(
        null=False,
        blank=False,
        error_messages={
            'blank': 'O campo Site de referência é obrigatório.',
            'invalid': 'O campo Site de referência deve conter um endereço web válido.'
        }
    )
    
    data_hora_entrevista = models.DateTimeField(
        null=True,
        blank=True,
        error_messages={
            'invalid': 'O campo Data e horário da entrevista deve conter uma data e horário válidos. Ex.: dia/mês/ano horas:minutos',
            'invalid_datetime': 'O campo Data e horário da entrevista deve conter uma data e horário válidos. Ex.: dia/mês/ano horas:minutos'
        }
    )

    situacao = models.CharField(
        null=False,
        blank=False,
        max_length=1,
        choices=Status.choices,
        default=Status.APPLIED,
        error_messages={
            'blank': 'O campo Situação é obrigatório.',
            'invalid_choice': 'O campo Situação contém um valor inválido.',
        },
    )

    data_hora_cadastro = models.DateTimeField(auto_now_add=True)
    
    data_hora_atualizacao = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        """
        Return user-friendly representation of this model.

        :return: str
        """
        return self.empresa_nome
    
    def get_absolute_url(self) -> str:
        """
        Return the canonical URL for this model instance.

        :return: str
        """
        return f'/oportunidades/{str(self.id)}'
    
    def clean(self):
        if self.situacao == self.Status.INTERVIEW_SCHEDULED and self.data_hora_entrevista is None:
            raise ValidationError({
                'data_hora_entrevista': ValidationError(
                    "O campo Data e o horário da entrevista deve ser preenchido caso a situação do cadastro seja 'Entrevista agendada'.",
                    code='required'
                )
            })
        
        if isinstance(self.data_hora_entrevista, datetime):
        
            if self.situacao == self.Status.APPLIED:
                raise ValidationError({
                    'data_hora_entrevista': ValidationError(
                        "O campo Data e horário da entrevista deve estar vazio caso a situação do cadastro seja 'Candidatado'.",
                        code='invalid_datetime'
                    )
                })
        
            if self.pk is None and not is_equal_to_or_later_than_current_datetime(self.data_hora_entrevista):
                raise ValidationError({
                    'data_hora_entrevista': ValidationError(
                        'O campo Data e horário da entrevista não pode ser anterior à data e ao horário atuais.',
                        code='invalid_datetime'
                    )
                })

services/web/src/vagas/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.urls import reverse
from django.utils import timezone
from vagas.forms import CadastroVagasForm, OportunidadesFilterForm
from vagas.models import Vaga

def index(request):
    form = OportunidadesFilterForm()
    situacoes = {
        Vaga.Status.APPLIED.value: Vaga.Status.APPLIED,
        Vaga.Status.WAITING.value: Vaga.Status.WAITING,
        Vaga.Status.INTERVIEW_SCHEDULED.value: Vaga.Status.INTERVIEW_SCHEDULED,
        Vaga.Status.REJECTED.value: Vaga.Status.REJECTED,
        Vaga.Status.APPROVED.value: Vaga.Status.APPROVED,
    }
    situacao_query = request.GET.get('situacao')
    situacao = situacoes.get(situacao_query)
    data_hora_cadastro_order = request.GET.get('data_hora_cadastro_order')

    if situacao:
        form.fields['situacao'].initial = situacao
        vagas = Vaga.objects.filter(situacao=situacao)
    else:
        form.fields['situacao'].initial = (None, 'Todas',)
        vagas = Vaga.objects
    
    if data_hora_cadastro_order == OportunidadesFilterForm.DataHoraCadastroOrder.OLDEST.value:
        form.fields['data_hora_cadastro_order'].initial = OportunidadesFilterForm.DataHoraCadastroOrder.OLDEST
        vagas = vagas.order_by('data_hora_cadastro')
    else:
        form.fields['data_hora_cadastro_order'].initial = OportunidadesFilterForm.DataHoraCadastroOrder.NEWEST
        vagas = vagas.order_by('-data_hora_cadastro')

    return render(request, 'homepage.html', {'vagas': vagas, 'form': form})

def delete_view(request, pk: int):
    vaga = get_object_or_404(Vaga, pk=pk)

    if request.method == 'POST':
        vaga.delete()
        messages.add_message(request, messages.SUCCESS, 'Vaga removida com sucesso.')

        return redirect(reverse('homepage'))

    return render(request, 'oportunidades_delete.html', {'vaga': vaga})

def edit_view(request, pk: int):
    vaga = get_object_or_404(Vaga, pk=pk)
    form = CadastroVagasForm(initial={
        'empresa_nome': vaga.empresa_nome,
        'empresa_endereco': vaga.empresa_endereco,
        'empresa_email': vaga.empresa_email,
        'empresa_site': vaga.empresa_site,
        'empresa_telefone_celular': vaga.empresa_telefone_celular,
        'empresa_telefone_comercial': vaga.empresa_telefone_comercial,
        'cargo_titulo': vaga.cargo_titulo,
        'cargo_descricao': vaga.cargo_descricao,
        'site_referencia': vaga.site_referencia,
        'data_hora_entrevista': timezone.localtime(vaga.data_hora_entrevista).strftime('%d/%m/%Y %H:%M') if vaga.data_hora_entrevista is not None else '',
        'situacao': vaga.situacao,
    })

    if request.method == 'POST':
        form = CadastroVagasForm(request.POST)

        if form.is_valid():
            vaga.empresa_nome = form.cleaned_data['empresa_nome']
            vaga.empresa_endereco = form.cleaned_data['empresa_endereco']
            vaga.empresa_email = form.cleaned_data['empresa_email']
            vaga.empresa_site = form.cleaned_data['empresa_site']
            vaga.empresa_telefone_celular = form.cleaned_data['empresa_telefone_celular']
            vaga.empresa_telefone_comercial = form.cleaned_data['empresa_telefone_comercial']
            vaga.cargo_titulo = form.cleaned_data['cargo_titulo']
            vaga.cargo_descricao = form.cleaned_data['cargo_descricao']
            vaga.site_referencia = form.cleaned_data['site_referencia']
            vaga.data_hora_entrevista = form.cleaned_data['data_hora_entrevista']
            vaga.situacao = form.cleaned_data['situacao']
            vaga.save()
            messages.add_message(request, messages.SUCCESS, 'Vaga atualizada com sucesso.')

            return redirect(reverse('oportunidades_detail', args=[str(vaga.pk)]))
        else:
            messages.add_message(request, messages.ERROR, 'Ocorreu um erro ao atualizar o cadastro. Por favor, verifique os dados preenchidos.')

    return render(request, 'oportunidades_edit.html', {'form': form})

def detail_view(request, pk: int):
    vaga = get_object_or_404(Vaga, pk=pk)
    
    return render(request, 'oportunidades_detail.html', {'vaga': vaga})

def create_view(request):
    form = CadastroVagasForm()
    
    if 'POST' == request.method:
        form = CadastroVagasForm(request.POST)

        if form.is_valid():
            vaga = Vaga.objects.create(
                empresa_nome=form.cleaned_data['empresa_nome'],
                empresa_endereco=form.cleaned_data['empresa_endereco'],
                empresa_email=form.cleaned_data['empresa_email'],
                empresa_site=form.cleaned_data['empresa_site'],
                empresa_telefone_celular=form.cleaned_data['empresa_telefone_celular'],
                empresa_telefone_comercial=form.cleaned_data['empresa_telefone_comercial'],
                cargo_titulo=form.cleaned_data['cargo_titulo'],
                cargo_descricao=form.cleaned_data['cargo_descricao'],
                site_referencia=form.cleaned_data['site_referencia'],
                data_hora_entrevista=form.cleaned_data['data_hora_entrevista'],
                situacao=form.cleaned_data['situacao'],
            )
            messages.add_message(request, messages.SUCCESS, 'Vaga registrada com sucesso.')
            
            return redirect(reverse('oportunidades_detail', args=[str(vaga.id)]))
        else:
            messages.add_message(request, messages.ERROR, 'Ocorreu um erro no cadastro. Por favor, verifique os dados preenchidos.')
    
    return render(request, 'oportunidades_new.html', {'form': form})

services/web/src/vagas/templates/cadastro_vagas_form.html
{% if form.non_field_errors %}

<div class="alert alert-danger my-5" role=alert>
{% for error in form.non_field_errors %}

<p class=m-0>{{ error|safe }}</p>

{% endfor %}
</div>

{% endif %}

{% for field in form %}
    <div class="row mb-5 align-items-center">
        <label for="{{ field.id_for_label }}" class="col-md-4 col-xl-3 col-form-label">{{ field.label }}</label>

        {% if field.html_name == 'cargo_descricao' %}
        <div class="col-md-8 col-xl-7">
        {% else %}
        <div class="col-md-5 col-xl-4">
        {% endif %}

            {{ field }}

            {% if field.errors %}
                {% for error in field.errors %}
                <div id="{{ field.html_name }}_error" class="invalid-feedback glacial-bold">
                    {{ error|safe }}
                </div>
                {% endfor %}
            {% endif %}
        </div>

        {% if field.field.required or field.help_text %}
        <div class="col-md-3 col-xl-4">
            <div class="form-text">
                {% if field.field.required %}
                <span id="{{ field.html_name }}_required" class="d-block text-muted">* Campo obrigatório</span>
                {% endif %}
                {% if field.help_text %}
                <span id="{{ field.html_name }}_help" class="d-block">{{ field.help_text|safe }}</span>
                {% endif %}
            </div>
        </div>
        {% endif %}
    </div>
{% endfor %}

services/web/src/vagas/templates/homepage.html
{% extends '_base.html' %}

{% block content %}
<div class="row">
    <div class="col">
        <h2 class="antonio-regular my-4">Oportunidades de vagas</h2>

        <form action method=get>
            {{ form }}
        </form>

        <div class=table-responsive>
            <table class="table table-hover caption-top">
                <caption class="glacial-bold">Lista de oportunidades de vagas. Total: {{ vagas | length }}</caption>
                <thead class="bg-beige align-top antonio-bold">
                    <tr>
                        <th scope=col>Empresa</th>
                        <th scope=col class="d-none d-md-table-cell">Cargo</th>
                        <th scope=col>Situação</th>
                        <th scope=col class="d-none d-lg-table-cell">Entrevista em</th>
                        <th scope=col class="d-none d-lg-table-cell">Cadastrada em</th>
                        <th scope=col class=text-center>Ações</th>
                    </tr>
                </thead>
                <tbody class=align-middle>
                    {% for vaga in vagas %}

                    {% if vaga.situacao == vaga.Status.WAITING %}
                    <tr class=table-secondary>
                        {% elif vaga.situacao == vaga.Status.INTERVIEW_SCHEDULED %}
                    <tr class=table-info>
                        {% elif vaga.situacao == vaga.Status.APPROVED %}
                    <tr class="table-success">
                        {% elif vaga.situacao == vaga.Status.REJECTED %}
                    <tr class=table-danger>
                        {% endif %}

                        <td><a target=_blank href="{{ vaga.empresa_site }}" rel="external"
                                class="link-dark">{{ vaga.empresa_nome }}</a></td>
                        <td class="d-none d-md-table-cell"><a href="{% url 'oportunidades_detail' vaga.pk %}"
                                class="link-dark">{{ vaga.cargo_titulo }}</a></td>
                        <td>{{ vaga.get_situacao_display }}</td>
                        <td class="d-none d-lg-table-cell">{% if vaga.data_hora_entrevista %}
                            {{ vaga.data_hora_entrevista | date:"d/m/Y H:i" }} {% endif %}</td>
                        <td class="d-none d-lg-table-cell">{{ vaga.data_hora_cadastro | date:"d/m/Y H:i" }}</td>
                        <td class="text-center glacial-bold"><a class="btn btn-primary btn-sm m-2"
                                href="{% url 'oportunidades_edit' vaga.pk %}">Atualizar</a><a
                                class="btn btn-danger btn-sm m-2"
                                href="{% url 'oportunidades_delete' vaga.pk %}">Excluir</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

services/web/src/vagas/templates/oportunidades_delete.html
{% extends '_base.html' %}

{% block title %}Remover vaga - {% endblock %}

{% block content %}
<div class=row>
    <div class=col>
        <h2 class="antonio-regular my-4">Tem certeza que deseja excluir este cadastro?</h2>

        <div class="card bg-light">
            <div class=card-body>
                <h3 class="card-title text-center antonio-bold">{{ vaga.empresa_nome }}</h3>
                <h4 class="card-subtitle text-muted glacial-bold text-center">{{ vaga.cargo_titulo }}</h4>

                {% if vaga.cargo_descricao %}
                <p class=card-text>{{ vaga.cargo_descricao | linebreaks }}</p>
                {% endif %}
            </div>
            <ul class="list-group list-group-flush text-center">
                {% if vaga.empresa_endereco %}
                 <li class="list-group-item">{{ vaga.empresa_endereco }}</li>
                 {% endif %}

                 {% if vaga.empresa_email %}
                 <li class="list-group-item">{{ vaga.empresa_email | urlize }}</li>
                 {% endif %}

                 <li class="list-group-item">{{ vaga.empresa_site | urlize }}</li>

                 {% if vaga.empresa_telefone_celular or vaga.empresa_telefone_comercial %}
                 <li class="list-group-item">
                     {% if vaga.empresa_telefone_celular %}
                     {{ vaga.empresa_telefone_celular }} |
                     {% endif %}
                     {% if vaga.empresa_telefone_comercial %}
                     {{ vaga.empresa_telefone_comercial }}
                     {% endif %}
                </li>
                 {% endif %}

                 <li class="list-group-item">Referência: {{ vaga.site_referencia | urlize }}</li>
                 <li class="list-group-item">Situação: {{ vaga.get_situacao_display }}</li>
                 
                 {% if vaga.data_hora_entrevista %}
                <li class="list-group-item">Entrevista em {{ vaga.data_hora_entrevista | date:"d/m/Y H:i"}}</li>
                {% endif %}
            </ul>
            <div class="card-footer glacial-bold text-muted">
                <small class=d-block>Cadastrada em: {{ vaga.data_hora_cadastro | date:"d/m/Y H:i" }}</small>
                <small class=d-block>Última atualização em: {{ vaga.data_hora_atualizacao | date:"d/m/Y H:i" }}</small>
            </div>
        </div>
    </div>
</div>

<div class="row text-center my-5">
    <div class=col>
        <form action method=post>
            {% csrf_token %}
            <input class="btn btn-lg btn-danger" type=submit value="Excluir cadastro">
        </form>
    </div>
</div>
{% endblock %}

services/web/src/vagas/templates/oportunidades_detail.html
{% extends '_base.html' %}

{% block title %}Detalhes da vaga - {% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <h2 class="antonio-regular my-4">Detalhes da vaga</h2>

        <div class="card bg-light">
            <div class=card-body>
                <h3 class="card-title text-center antonio-bold">{{ vaga.empresa_nome }}</h3>
                <h4 class="card-subtitle text-muted glacial-bold text-center">{{ vaga.cargo_titulo }}</h4>

                {% if vaga.cargo_descricao %}
                <p class=card-text>{{ vaga.cargo_descricao | linebreaks }}</p>
                {% endif %}
            </div>
            <ul class="list-group list-group-flush text-center">
                {% if vaga.empresa_endereco %}
                 <li class="list-group-item">{{ vaga.empresa_endereco }}</li>
                 {% endif %}

                 {% if vaga.empresa_email %}
                 <li class="list-group-item">{{ vaga.empresa_email | urlize }}</li>
                 {% endif %}

                 <li class="list-group-item">{{ vaga.empresa_site | urlize }}</li>

                 {% if vaga.empresa_telefone_celular %}
                 <li class="list-group-item">Tel. celular: {{ vaga.empresa_telefone_celular }}</li>
                 {% endif %}

                 {% if vaga.empresa_telefone_comercial %}
                 <li class="list-group-item">Tel. comercial: {{ vaga.empresa_telefone_comercial }}</li>
                 {% endif %}

                 <li class="list-group-item">Referência: {{ vaga.site_referencia | urlize }}</li>
                 <li class="list-group-item">Situação: {{ vaga.get_situacao_display }}</li>
                 
                 {% if vaga.data_hora_entrevista %}
                <li class="list-group-item">Entrevista em {{ vaga.data_hora_entrevista | date:"d/m/Y H:i"}}</li>
                {% endif %}

                <li class="list-group-item">
                    <a class="btn btn-primary btn-lg mx-4 my-3" href="{% url 'oportunidades_edit' vaga.pk %}">Atualizar</a>
                    <a class="btn btn-danger btn-lg mx-4 my-3" href="{% url 'oportunidades_delete' vaga.pk %}">Excluir</a>
                </li>
            </ul>
            <div class="card-footer glacial-bold text-muted">
                <small class=d-block>Cadastrada em: {{ vaga.data_hora_cadastro | date:"d/m/Y H:i" }}</small>
                <small class=d-block>Última atualização em: {{ vaga.data_hora_atualizacao | date:"d/m/Y H:i" }}</small>
            </div>
        </div>
    </div>
</div>
{% endblock %}

services/web/src/vagas/templates/oportunidades_edit.html
{% extends '_base.html' %}

{% load static %}

{% block title%}Atualizar vaga - {% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'fontawesome-5.0.1/css/fontawesome-all.min.css' %}">
<link rel="stylesheet" href="{% static 'datetimepicker/css/bootstrap-datetimepicker.min.css' %}">
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <h2 class="antonio-regular my-4">Atualização de vaga</h2>
        <form action method=post>
            {% csrf_token %}

            {{ form }}

            <div class="d-flex justify-content-center py-4">
                <input type=submit value="Atualizar" class="btn btn-primary btn-lg">
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'datetimepicker/js/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'datetimepicker/js/locales/bootstrap-datetimepicker.pt-BR.js' %}"></script>
<script src="{% static 'jquery.mask.min.js' %}"></script>
<script src="{% static 'main.js' %}"></script>
{% endblock %}

services/web/src/vagas/templates/oportunidades_filter_form.html
<div class="row mb-4 row-cols-lg-auto align-items-start align-items-lg-center justify-content-end">
    {% for field in form %}
    <div class="col-5">
        <label for="{{ field.id_for_label }}" class="col-form-label-sm py-0">{{ field.label }}</label>
    </div>
    <div class="col-7 mb-3 mb-lg-0">
        {{ field }}
    </div>
    {% endfor %}
    <div class="col-12 mt-3 mt-md-0">
        <input type=submit value=Filtrar class="btn btn-primary btn-sm glacial-bold">
    </div>
</div>

services/web/src/vagas/templates/oportunidades_new.html
{% extends '_base.html' %}

{% load static %}

{% block title %}Cadastro de vaga - {% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'fontawesome-5.0.1/css/fontawesome-all.min.css' %}">
<link rel="stylesheet" href="{% static 'datetimepicker/css/bootstrap-datetimepicker.min.css' %}">
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <h2 class="antonio-regular my-4">Cadastro de oportunidade de vaga</h2>
        <form action method=post>
            {% csrf_token %}
            
            {{ form }}

            <div class="d-flex justify-content-center py-4">
                <input type=submit value="Cadastrar oportunidade" class="btn btn-primary btn-lg">
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'datetimepicker/js/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'datetimepicker/js/locales/bootstrap-datetimepicker.pt-BR.js' %}"></script>
<script src="{% static 'jquery.mask.min.js' %}"></script>
<script src="{% static 'main.js' %}"></script>
{% endblock %}